name: Build docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [
          {arch: 'linux/amd64', tag: 'develop'},
          {arch: 'linux/arm64', tag: 'develop-arm64'}]
        container: [
          {name: 'aio-fail2ban', context: './'}]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            szaimen/${{ matrix.container.name }}
          tags: |
            ${{ matrix.platform.tag }}

      - name: Build docker image and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.container.context }}
          platforms: ${{matrix.platform.arch}}
          no-cache: true
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          provenance: false
          # Needed since when on default 'application/vnd.oci.image.index.v1+json' is used which does not work with "docker manifest create" (multiarch)
          # TODO make it work with default value