name: Promote to latest

on:
  workflow_dispatch:

jobs:
  promote_to_latest:
    runs-on: ubuntu-latest
    name: Promote from beta to latest 
    
    strategy:
      fail-fast: false
      matrix:
        name: ['aio-fail2ban']

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Promote images from beta to latest
      run: |
        set -x
        AIO_NAME=${{ matrix.name }}
        DOCKER_HUB_ORG=szaimen
        set +x

        docker buildx imagetools create --tag "$DOCKER_HUB_ORG"/$AIO_NAME\:latest "$DOCKER_HUB_ORG"/$AIO_NAME\:beta
