name: Promote to beta

on:
  workflow_dispatch:

jobs:
  promote_to_latest:
    runs-on: ubuntu-latest
    name: Promote from develop to beta 
    
    strategy:
      fail-fast: false
      matrix:
        name: ['aio-fail2ban']

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Promote images from develop to beta (create multiarch)
      run: |
        set -x
        AIO_NAME=${{ matrix.name }}
        DOCKER_HUB_ORG=szaimen
        set +x
        
        # create multiarch image
        docker manifest create "$DOCKER_HUB_ORG"/$AIO_NAME\:beta -a "$DOCKER_HUB_ORG"/$AIO_NAME\:develop -a "$DOCKER_HUB_ORG"/$AIO_NAME\:develop-arm64
        docker manifest push "$DOCKER_HUB_ORG"/$AIO_NAME\:beta
